### ISSUE TITLE
Corrupt CI package caching

### ISSUE THREAD

**Issue by dengjeffrey** [Shopify/unity-buy-sdk#101]
It seems like the Unity and iOS Editor Support packages are always corrupt after caching on the CI, causing the install script to fail.

**Comment by mikkoh** [comment]
How big is the download for support packages?

**Comment by dengjeffrey** [comment]
2 GB

**Comment by mikkoh** [comment]
@dengjeffrey I'm going to close this since we're moving to buildkit.
