### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by dengjeffrey** [Shopify/unity-buy-sdk#105]
Discussed with @sleroux and @mikkoh, we would like to handler errors in a consistent way throughout the SDK. 

We thought about handling the errors as a list of `ShopifyError` 
```C#
interface ShopifyError { // We leave this implementation empty for now }
delegate void Failure(List<ShopifyError>);

someCall( (errors) => {
    foreach (var error in errors) {
        if (error is httpError) {
        
        } else if (error is GraphQLError) {

        } else if (error is UserError) {

        }
    }
});
```

This way we gain the following:

+ By having `ShopifyError` as an interface we can add new functionality to all errors at any given time
+ Since the `If else` dance is unavoidable by using an array of errors we can return new types of errors without changing thing signature
    
The problems this solution causes:
+ The implementor does not know explicitly what possible errors can be returned, and which ones need to be handled

**Comment by mikkoh** [comment]
I wonder if we could use `Tuples` https://msdn.microsoft.com/en-us/library/system.tuple(v=vs.110).aspx

Tuples def aren't something that Unity devs use though :(

**Comment by sleroux** [comment]
Do you mean to use Tuples as the parameter type for errors instead of an array? Not sure if we can define a Tuple type with a variable number of entries. Would be cool though to wrap the errors into a single tuple though.

**Comment by dengjeffrey** [comment]
@richardmonette Feel free to give some opinions on this solution

**Comment by sleroux** [comment]
﻿As I'm starting to look more into this, I had a couple of additional ideas:

1. One way we could clean this up a bit a more more is to wrap the errors in a class so we don't return an array directly from the API.

2. I wonder if we need strongly typed errors for each error type. I'm probably missing something but for most errors we only need maybe a textual message along with a few other properties.

```csharp
class ShopifyError {
    enum Code {
        httpError, graphqlError, ...
    }

    public readonly Code code;

    // Textual message describing the error
    public readonly string reason;

    // Generic dictionary for putting more specific things in. Inspired by how iOS bubbles up various error types.
    public readonly Dictionary<String, Object> info;

    ...
}

class ShopifyFailure {
    public readonly List<ShopifyError> errors;
    public ShopifyFailure(List<ErrorInfo> errors) {
        this.errors = errors;
    }
}

// ... From the game dev's perspective ...
client.products((products, failure) => {
    if (failure != nil) {
        handleFailure(failure);
    }    
});

void handleFailure(ShopifyFailure failure) {
    foreach (var error in failure.errors) {
        switch (error.code) {
        case ShopifyError.Code.httpError:
            ...
        case ShopifyError.Code.graphqlError:
            ...
        }
    }) 
}
```

**Comment by richardmonette** [comment]
When there is some kind of failure, are we expecting that it will generally be composed of multiple errors? I'm just wondering if we are adding additional complexity around handling a failure which is composed of many errors, when in most cases the first error will halt execution, and need to be handled right away (as a single error). 

For something like form validation I can imagine we'd be collecting multiple errors, but if we have a httpError, would we really ever also have a graphqlError at the same time?

**Comment by dengjeffrey** [comment]
What exact specific things will we be putting in `info`? Should `public readonly string reason` be a list of reasons, so it works with `graphqlError` and `userError`?

**Comment by sleroux** [comment]
> For something like form validation I can imagine we'd be collecting multiple errors, but if we have a httpError, would we really ever also have a graphqlError at the same time?

I think @dengjeffrey mentioned that for GraphQL errors we can receive a list of errors that occurred. I'm not sure how often we would have multiple errors in the flow though. We can also make the choice to only surface one error at a time and mask the rest.

> What exact specific things will we be putting in info? 

Not sure. I think you mentioned yesterday that a `CheckoutError` would contain some additional information to give context to what happened? The info dictionary could be used for more context around an error. For example, for HTTP errors we can add the status code.

> Should public readonly string reason be a list of reasons, so it works with graphqlError and userError?

We could map each GraphQL error into it's own error (ie: GraphQLError(string1, string2, ...) -> GraphQLError(string1), GraphQLError(string2), ...) to keep our error model consistent across errors.

**Comment by dengjeffrey** [comment]
I was thinking that was what the `ShopifyFailure` class was for, we could subclass `ShopifyFailure` and create `CheckoutFailure` that would include extra information pertaining to a checkout. 

It might be worthwhile to have `info` added in later, since it would require a lot of work parsing the error strings and packaging them in a dictionary.

**Comment by sleroux** [comment]
> I was thinking that was what the ShopifyFailure class was for, we could subclass ShopifyFailure and create CheckoutFailure that would include extra information pertaining to a checkout.

Ya that's the approach that we talked about yesterday but the more I think about it the enum approach might be cleaner overall so developers can use a `switch` to handle each type. The additional thinking is the ability to store the properties we were going to subclass the error type for into the `info` dictionary. Downside is we would have to define specific keys to get out the checkout error stuff out of the dictionary.

> It might be worthwhile to have info added in later, since it would require a lot of work parsing the error strings and packaging them in a dictionary.

For the GraphQL errors I was just going to keep the error string we get back and store it in the reason variable. Not sure if there is any value in parsing out the string for bits of info unless I'm missing something?

**Comment by dengjeffrey** [comment]
+ I agree that the enum approach is better, but for cases like `CheckoutFailure` we should be open to subclassing. `CheckoutFailure` is a failure caused by an `error` or due to cancellation.  It can be represented by enums, `Error`, or `Cancelled`.  We could put `Error` and `Cancelled` into `info` but we would have to define specific keys like you mentioned.
``` 
// At the call site
Checkout( (CheckoutFailure failure) => {

    switch(failure.type) {
    case Cancelled:
    case Error:
        switch failure.error {
            case ApplePayError: // Fallback to Web
            case HTTPError: // ApplePay returned a token, but we couldn't reach our servers
            default: // SDK is Broken (UserError and GraphQL error)
        }
    }
})
```

+ I don't think having a List of Errors is a good idea anymore
     + We should only surface one explicit error, surfacing multiple errors in a list means we have to manage the order of that list also. If we don't manage the order of that list, the user has to itterate the entire list to figure out which error it should really be handling. 
     + The order of which error we surface should be represented by the order of which layer our stack calls first
          + ApplePay -> HTTP -> GraphQL -> UserError

**Comment by sleroux** [comment]
I really like all of these suggestions. If we don't have a list anymore we could simply go back to returning a ShopifyError directly instead of wrapping a list of errors in ShopifyFailure and have a sub class of that error for checkouts named CheckoutError. Combining the enum to identify the ShopifyError to switch on that sounds like the best of both worlds.

👍👍

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by mikkoh** [comment]
I wonder if there will be a case where we have a success response get returned but we have a user error. 😕

For instance lets say in the future we add the ability to set shipping information. The user drops in shipping info and requests a web checkout link. A web checkout link will be returned but also `userError` was also created.

Maybe this is an non issue if setting shipping info is an explicit query you have to perform before requesting the `webUrl`.
