### ISSUE TITLE
Consolidate Delegates

### ISSUE THREAD

**Issue by mikkoh** [Shopify/unity-buy-sdk#109]
Let's consolidate all delegate's to one file. This will allow us to have a high level overview of the entire application.

Also in doing this we should avoid `Actions` even though they can be convenient.

**Comment by mikkoh** [comment]
@JakeCataford FYI this will be happening

**Comment by sleroux** [comment]
https://github.com/Shopify/unity-buy-sdk/pull/110

**Comment by sleroux** [comment]
From Jeff's comment on the above PR:

As part of consolidating the delegates, we should also do an audit of how we are naming the delegates and following some kind of convention. Some examples are:

https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members
https://stackoverflow.com/questions/2346065/proper-naming-convention-for-a-net-delegate-type

**Comment by JakeCataford** [comment]
If you have a Delegate type (say, ProductHandler(Product product)) and two or more unrelated classes are using this handler, It closely binds the associated classes to that interface... now, this might not be such a bad thing, considering that it keeps us honest about the interfaces we are providing, but I think we should emphasize/organize around the _behaviour_ of the handler (`ProductFetchHandler(Product product) + ProductUpdateHandler(Product product)`) over its _structure_ (`ProductHandler(Product product)`). The reasoning behind this is that the interface will be consistent for similar behaviours, but might not be for similar structure (imagine we want the changed properties in the product update, this doesn't make sense for the product fetch case, so if they were one delegate type we would have to pry them apart)

**Comment by JakeCataford** [comment]
But im totally for condensing these under a single file or even in their own files (even though thats super verbose and kinda unnescesary)

**Comment by JakeCataford** [comment]
On a completely other side note im experimenting with getting omnisharp running lints on the project so we can have an enforced styleguide.

**Comment by sleroux** [comment]
Would it make sense to start a repo/somewhere to document our C# styleguide and resources? It would be great to have all of this in one place.

**Comment by JakeCataford** [comment]
yea I mean i think a good start would be to just provide the policies for the various editors... of course then we'd have to agree on a consistent style which is definitely opening the door and entering the bikeshed haha

**Comment by sleroux** [comment]
Opened a follow up issues to audit our delegate names. Closing this one as https://github.com/Shopify/unity-buy-sdk/pull/110 landed.
