### ISSUE TITLE
How do we handle driving people to signup?

### ISSUE THREAD

**Issue by mikkoh** [Shopify/unity-buy-sdk#155]
Hey. I've been researching about different ways that we could drive people to sign up. My original idea was to add components onto the global game object. Something like this:

<img width="1390" alt="screen shot 2017-07-06 at 1 19 48 pm" src="https://user-images.githubusercontent.com/496903/27927995-8c9f1d60-625b-11e7-9340-59b74f5479a0.png">

But I'm afraid that this isn't straightforward enough.

Then I explored what if brought up a pop up dialog once the Unity SDK was setup first. Something like this:

<img width="930" alt="screen shot 2017-07-06 at 1 29 02 pm" src="https://user-images.githubusercontent.com/496903/27928014-a45d599e-625b-11e7-8d50-ba3827bfd88c.png">

But somehow this felt too much in your face and once you've closed the window it's gone forever.

I then downloaded Game Sparks to see what they do. After installing their SDK I got the following Window pop up:

<img width="349" alt="screen shot 2017-07-06 at 2 34 45 pm" src="https://user-images.githubusercontent.com/496903/27928067-ccaec0e0-625b-11e7-8b7c-7cc765c12bf1.png">

And they added a menu:

<img width="400" alt="screen shot 2017-07-06 at 2 34 10 pm" src="https://user-images.githubusercontent.com/496903/27928082-d6e63a66-625b-11e7-9521-2625f707550d.png">

We could do all of this also. My only worry is if we add a menu item some developers might get upset about this. I know we could for instance drop these menu items under tools but I think it's too hidden then.

I just want to get ideas on what direction everyone thinks is the best.

@JakeCataford @dengjeffrey @sleroux @richardmonette @coreypollock

**Comment by sleroux** [comment]
I like the GameSparks SDK pane. It seems the less obtrusive out of the bunch. I'm not too familiar with how editor panes work but is there a way we can build a pre-signup and post-signup UI for it? It'd be cool if they could enter their accessToken and have the pane update to include links and other SDK info for their store. We could fold whatever options would live in a menu into the pane.

**Comment by JakeCataford** [comment]
Why not just a menu under `Window` like Shaderforge does? Non-intrusive and the best option for a configuration pane imo... 
![fullscreen_2017-07-06__3_29_pm](https://user-images.githubusercontent.com/2158003/27929204-f11dc6e8-625f-11e7-8ba8-8b0b90cde5b7.png)

**Comment by JakeCataford** [comment]
> editor panes work but is there a way we can build a pre-signup and post-signup UI for it? 

Yea but we would need something in their project to let us know that they have set up the creds/have the app installed. One example of how to accomplish this is to create a scriptableobject asset like `ShopifyApiCredentials` that contains the shop url and the storefront access token, and make it so you can feed that object to the api when creating a new client... then we just query the asset database for an object of that type, if they have one... its good! if not... it needs to be set up. We can also create this asset for them via the window as well. The hangup with this method is that we will need to instruct people to have a field for `ShopifyApiCredentials` on their behaviours that use the api, and pass that object in... we could just load it ourselves as a default case, but we would have to be careful to include it in a resources folder so its not clipped at build time.

**Comment by mikkoh** [comment]
@JakeCataford my issue with it being a sub menu item is that it'll be too hidden.

**Comment by JakeCataford** [comment]
So going forward with this I'm working on a solution that:

1. Builds a window, much like the gamesparks login, that pops up after installation. This window has a slightly different context however (for now). The idea is for this window to be more a "static" informational panel than an actionable form. It can link to documentation, provide a short introduction to the sdk and show users where to sign up for shopify/how to get set up.

2. A way to pull up this menu again via a `Shopify/About` menu or something similar.

I'm going to accomplish the popup by using https://docs.unity3d.com/ScriptReference/InitializeOnLoadAttribute.html to run a static method, and  `EditorPrefs` to store the popup seen state. I'll push a PR today with the code and we can chat about it there.

**Comment by JakeCataford** [comment]
Closed via https://github.com/Shopify/unity-buy-sdk/pull/192
