### ISSUE TITLE
Querying Shop fields

### ISSUE THREAD

**Issue by dengjeffrey** [Shopify/unity-buy-sdk#216]
### What is the issue?
Currently we/users have to query for the store name and other fields that live on the `Shop` field. Fields such as:

    Store Name
    Description
    Payment Settings
    ...

For making payments through Android and Apple Pay we need some of these fields, such as `Payment Settings` and `Store Name`

Since these fields rarely change within a single session, it doesn't make sense to query them all the time. So these fields need to sit somewhere in memory. 

### Current Solution
As implemented currently for `Payment Settings`, Cart saves a copy of `Payment Settings` when it fetches it for the first time. This is flawed since we can have multiple carts for the same `Shop`

We also have an asynchronous call in `ShopifyClient` that fetched `Payment Settings`
``` c#
public void paymentSettings(PaymentSettingsHandler callback) {
    var query = new QueryRootQuery();
    DefaultQueries.shop.PaymentSettings(query);

    Query(query, (response, error) => {
        if (error != null) {
            callback(null, error);
        } else {
            callback(response.shop().paymentSettings(), null);
        }
    });
}
```

Although this works fine now, if we implemented this for other fields it would become really messy if we wanted more than one. It also doesn't take advantage of GraphQL. Which is the case for native payments

```
paymentSettings((paymentSettings) => {
    name((name) => {
        ...
   }
})
```

This also creates the problem where we need to excessively overload the `Checkout` method of `INativeCheckout` and save `shopName` and `paymentSettings` in `INativeCheckout` after its constructor.

```c#
Checkout(string key, string shopName, PaymentSettings paymentSettings, CheckoutSuccessCallback success, CheckoutCancelCallback cancelled, CheckoutFailureCallback failure)
```

### Proposed Solution
It would make sense to store these fields on `ShopifyClient` instead of `Cart` since a client essentially represents a unique shop domain.

Instead of deferring the querying of  `shop.paymentSettings` and `shop.name` we can place this within `ShopifyBuy.Init` 

```c#
/// Instead of 
/// ShopifyBuy.Init(accessToken, shopDomain);

/// We will query Shop meta data in the init phase
ShopifyBuy.Init(accessToken, shopDomain, completion: (shopifyClient, shopifyError) => {

});

```

#### What does this solve
1. Static shop data now lives in a appropriate class and is stored in memory.
2. The constructor for `INativeCheckout` can now be given `shop.name` and `shop.paymentSettings`
3. `CanCheckoutWithNativePay` no longer needs to be asynchronous
4. We can efficiently query `shop` using one call. 
5. This allows the user to query other data they may need from `Shop` efficiently by adding to `Init`
6. Users can find out if their domain and access token are valid upon `Init` before use

#### What problems are caused by this solution
1. This forces all users of our SDK to query for these extra fields
2. Init is no longer a synchronous call  

<hr>
I've been thinking about this issue for a while now, let me know your thoughts and concerns 😬 
@richardmonette @sleroux

**Comment by sleroux** [comment]
This sounds like an elegant solution to our current problem. Looking at the list of cons: 

> This forces all users of our SDK to query for these extra fields

This is fine. IIUC this means that we make one additional query in the SDK when not all users need this information right? For the cost of one request I don't really see this being an issue. 

> Init is no longer a synchronous call

I think this is okay but we probably want to rename this method to something more meaningful like `BuildClient`. Also, going this route breaks our singleton model a bit by having the developer interact with the Client mostly instead of getting a handle to it through `ShopifyBuy` which is probably okay.

**Comment by dengjeffrey** [comment]
@sleroux  They will still be able to use `ShopifyBuy,Client()`, currently `Init` actually returns an instance of `ShopifyClient`

**Comment by richardmonette** [comment]
In the proposal, there is a completion callback, do we also need to have a failure case, in case the initialization query for some reasons fails (network error, etc.)?

**Comment by dengjeffrey** [comment]
@richardmonette Good catch, yes I will add that in

**Comment by richardmonette** [comment]
Otherwise, lgtm

**Comment by mikkoh** [comment]
One nice thing about having `Init` be synchronous is that we could initialize already in the Unity GUI. I'm not sure we should make `Init` be asynchronous. What if instead on the first query that a user performs we perform the initialization query. Basically the client would check a boolean to see if it's initialized and then just query the init query.

My gut feeling though is that in specific for getting the `PaymentSettings` I think its fine we don't query it until we need that data. I do think that `paymentSettings` should not be a public method.

**Comment by dengjeffrey** [comment]
Main concern with having the first query perform an init query, is that we would be setting public variables such as `paymentSettings` and `name` after the init query has completed. Since these variables are public, it's misleading if they are not officially initialized till after the first query.

Especially if someone wanted the name after init
```
ShopifyBuy.Init()
// Since we never made a query, name is empty
ShopifyBuy.Client().Name;
```

Perhaps we can keep `name`, and `paymentSettings` private in cart as you suggested. And overloading the `Checkout` perhaps with a struct. This way we don't query it until we need the data.
```C#
struct StoreMeta {
    string shopName;
    PaymentSettings paymentSettings;
}

Checkout(string key, StoreMeta meta, CheckoutSuccessCallback success, CheckoutCancelCallback cancelled, CheckoutFailureCallback failure)

```

**Comment by mikkoh** [comment]
#230 for now just removes `paymentSettings` from the client. I think later on if we find we need an `init` query we can add it under the hood.

I think in general queries added to `Client` should be useful to the end user and it should be something they use often.
