### ISSUE TITLE
Large product requests causing GraphQL timeouts

### ISSUE THREAD

**Issue by sleroux** [Shopify/unity-buy-sdk#370]
Whenever we make a fetch products request to the Storefront API with >= 250 products, we get back a Timeout error. We currently cap the number of products requested for when calling the default `ShopifyBuy.Client().products(..)` to 250 but it seems that even this number is causing timeouts. Since the API supports paging, we should:

1. Decrease the default cap of number of products we ask for to avoid timeouts.
2. Add documentation for using the paging API for getting products

**Comment by evgeny127** [comment]
Hi, 
I still not fixed issue.
ShopifyBuy.Client().products(..)
How can we set limit count on fetch products from shopify?
Also how SDK supports page fetch?
Could you tell me more clearly?

**Comment by mikkoh** [comment]
@evgeny127 we're currently working on this #387 will implement product pagination

**Comment by mikkoh** [comment]
We're pooling everything related to pagination in this branch if interested https://github.com/Shopify/unity-buy-sdk/tree/pagination

**Comment by sleroux** [comment]
We've since limited this query to use the first 20 instead of 250.
