### ISSUE TITLE
Run Integration tests via command line

### ISSUE THREAD

**Issue by mikkoh** [Shopify/unity-buy-sdk#43]
Tooling for Integration tests seem stable enough to maybe run in CI. The first step would be to implement the ability to run Integration tests via command line and evaluate how stable that is.

**Comment by sleroux** [comment]
Integration tests are working with Unity 2017 and up so I'm going to go ahead and close this for now.

**Comment by mikkoh** [comment]
Yeah so much has changed with the Unity test runner.
