### ISSUE TITLE
Exclude Wallet API permissions from app when not using Android Pay

### ISSUE THREAD

**Issue by sleroux** [Shopify/unity-buy-sdk#497]
Currently the SDK contains the native pay module as a dependency but we haven't enabled Android Pay yet. Since the dependency is being brought in, it's AndroidManifest permissions are also being copied over which includes `com.google.android.gms.wallet.api.enabled`. Apps have a chance of being rejected if they are including the Wallet API permissions without actually using the wallet features. 

We need a way to exclude this dependency for now until Android Pay is enabled. We should also consider having a way to exclude it all together even when the feature finishes in case developer wish to only stick with web checkouts.

**Comment by nasir41** [comment]
I'm facing the same issue I'm not using androidpay but this permission is already there in sdk.
Please help me how I can remove this permission and avoid rejection of my app?

**Comment by sleroux** [comment]
This issue shouldn't be a problem with the latest release as we've removed the Android Pay functionality from the SDK for now. Try giving the latest release a go and let me know if that resolves the permissions issue.

**Comment by sleroux** [comment]
I created a few test builds using both the internal build chain and gradle from Unity and opened up the .AAR files with Android Studio to see if the generated manifest file contained the wallet permission and it doesn't seem to be the case. I'm going to go ahead and close this for now.
