### ISSUE TITLE
Trouble Building for Android - Build Details out of date?

### ISSUE THREAD

**Issue by kdbolt70** [Shopify/unity-buy-sdk#507]
Hello,

I am trying to integrate with Unity 2017.3.1, but cannot get my app to build for Android. I've updated my gradle file with the information in the build details page [here](https://github.com/Shopify/unity-buy-sdk/blob/master/BUILDDETAILS.md#android), however I get the following error:

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gradleOut'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find :shopify_buy_plugin:.
     Searched in the following locations:
         file:/C:/Users/Kevin/AppData/Local/Android/Sdk/extras/android/m2repository//shopify_buy_plugin//shopify_buy_plugin-.pom
         file:/C:/Users/Kevin/AppData/Local/Android/Sdk/extras/android/m2repository//shopify_buy_plugin//shopify_buy_plugin-.aar
         file:/G:/SightWeave/DimensionallyYours/DimensionallyYours/Temp/gradleOut/sdk-manager//shopify_buy_plugin//shopify_buy_plugin-.aar
     Required by:
         project :
   > Could not find com.android.support:appcompat-v7:26.0.0.
     Searched in the following locations:
         file:/C:/Users/Kevin/AppData/Local/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.0.0/appcompat-v7-26.0.0.pom
         file:/C:/Users/Kevin/AppData/Local/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.0.0/appcompat-v7-26.0.0.jar
         file:/G:/SightWeave/DimensionallyYours/DimensionallyYours/Temp/gradleOut/sdk-manager/com/android/support/appcompat-v7/26.0.0/appcompat-v7-26.0.0.jar
     Required by:
         project :
   > Could not find com.android.support:customtabs:26.0.0.
     Searched in the following locations:
         file:/C:/Users/Kevin/AppData/Local/Android/Sdk/extras/android/m2repository/com/android/support/customtabs/26.0.0/customtabs-26.0.0.pom
         file:/C:/Users/Kevin/AppData/Local/Android/Sdk/extras/android/m2repository/com/android/support/customtabs/26.0.0/customtabs-26.0.0.jar
         file:/G:/SightWeave/DimensionallyYours/DimensionallyYours/Temp/gradleOut/sdk-manager/com/android/support/customtabs/26.0.0/customtabs-26.0.0.jar
     Required by:
         project :
   > Could not find com.shopify.mobilebuysdk:buy3-pay-support:1.0.0.
     Searched in the following locations:
         file:/C:/Users/Kevin/AppData/Local/Android/Sdk/extras/android/m2repository/com/shopify/mobilebuysdk/buy3-pay-support/1.0.0/buy3-pay-support-1.0.0.pom
         file:/C:/Users/Kevin/AppData/Local/Android/Sdk/extras/android/m2repository/com/shopify/mobilebuysdk/buy3-pay-support/1.0.0/buy3-pay-support-1.0.0.jar
         file:/G:/SightWeave/DimensionallyYours/DimensionallyYours/Temp/gradleOut/sdk-manager/com/shopify/mobilebuysdk/buy3-pay-support/1.0.0/buy3-pay-support-1.0.0.jar
     Required by:
         project :
   > Could not find com.squareup.moshi:moshi:1.5.0.
     Searched in the following locations:
         file:/C:/Users/Kevin/AppData/Local/Android/Sdk/extras/android/m2repository/com/squareup/moshi/moshi/1.5.0/moshi-1.5.0.pom
         file:/C:/Users/Kevin/AppData/Local/Android/Sdk/extras/android/m2repository/com/squareup/moshi/moshi/1.5.0/moshi-1.5.0.jar
         file:/G:/SightWeave/DimensionallyYours/DimensionallyYours/Temp/gradleOut/sdk-manager/com/squareup/moshi/moshi/1.5.0/moshi-1.5.0.jar
     Required by:
         project :`

Also, the Build Details page references a mainTemplate.gradle file that no longer exists. I'm very new to building for Android so I apologize for my lack of knowledge. It looks like the dependencies may have changed since that document was made? Thanks!

**Comment by sleroux** [comment]
Hey @kdbolt70!

Thanks for filing a issue. You're correct - it looks like our Android build information is out of date for the plugin. I've gone ahead and updated it as part of fix I'm working on. You used to have to specify some custom things around Gradle and `mainTemplate.gradle` but that's not longer the case. Your application should be able to build with _any_ of the build systems supported by Unity for Android.

Looks like the issue you're running into in particular is related to the plugin's inability to fetch it's own dependencies. I've submitted a fix that looks to be building for me in Unity 2017.3.1 but I want to make sure it'll work for you before I go ahead and land it.

Would you mind importing https://github.com/Shopify/unity-buy-sdk/blob/399acee3ffdd70062d7ef10b98952a5d1a37bfeb/shopify-buy.unitypackage into your project and try building for Android? Probably be best to use the `internal` build system.

**Comment by kdbolt70** [comment]
Was able to import the latest package and build! Will be testing the deployment to my device tonight. Thanks!

**Comment by sleroux** [comment]
Awesome 👍 Thanks for trying it out! I'll land a fix shortly with a new release.

**Comment by kdbolt70** [comment]
Thanks for the fix! Was able to successfully deploy to my S9+.
