### ISSUE TITLE
Unity Android : com.shopify.buy.androidpay.AndroidPayCheckout class not found

### ISSUE THREAD

**Issue by nasir41** [Shopify/unity-buy-sdk#510]
When I run my Unity App on android with example scene following error pop up.
java.lang.NoClassDefFoundError: com.shopify.buy.androidpay.AndroidPayCheckout

Here are logs this error occure when I click on "Add to Cart" on my android device.
java.lang.NoClassDefFoundError: com.shopify.buy.androidpay.AndroidPayCheckout
        at com.shopify.buy.androidpay.AndroidPayHelper.getCheckout(AndroidPayHelper.java:19)
        at com.shopify.buy.androidpay.AndroidPayCheckoutSession.<init>(AndroidPayCheckoutSession.java:54)
        at com.shopify.buy.androidpay.AndroidPayCheckoutSession.<init>(AndroidPayCheckoutSession.java:45)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.a(Unknown Source)
        at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:179)

**Comment by nasir41** [comment]
Steps to reproduce the issue:
1- Create an empty project
2-Import the latest shopify unity package -> shopify-buy.unitypackage
3- After resolving jar client export the project to Android Studio because on my system Unity does not build with latest build tools.
4- After importing the unity project to Android Studio change the 
Target SDK version to 26
compileSdkVersion 26
buildToolsVersion '26.0.2'
dependencies {
		classpath 'com.android.tools.build:gradle:2.3.3'
}
5- Now build will be successful if you have imported all the required jar files properly here are all my jar files which I have imported using gradle dependency.
dependencies {
	compile fileTree(dir: 'libs', include: ['*.jar'])
	compile(name: 'buy3-pay-support-1.0.2', ext:'aar')
	compile(name: 'com.android.support.animated-vector-drawable-26.0.0', ext:'aar')
	compile(name: 'com.android.support.appcompat-v7-26.0.0', ext:'aar')
	compile(name: 'com.android.support.constraint.constraint-layout-1.0.2', ext:'aar')
	compile(name: 'com.android.support.customtabs-26.0.0', ext:'aar')
	compile(name: 'com.android.support.design-26.0.0', ext:'aar')
	compile(name: 'com.android.support.recyclerview-v7-26.0.0', ext:'aar')
	compile(name: 'com.android.support.support-compat-26.0.0', ext:'aar')
	compile(name: 'com.android.support.support-core-ui-26.0.0', ext:'aar')
	compile(name: 'com.android.support.support-core-utils-26.0.0', ext:'aar')
	compile(name: 'com.android.support.support-fragment-26.0.0', ext:'aar')
	compile(name: 'com.android.support.support-media-compat-26.0.0', ext:'aar')
	compile(name: 'com.android.support.support-v4-26.0.0', ext:'aar')
	compile(name: 'com.android.support.support-vector-drawable-26.0.0', ext:'aar')
	compile(name: 'com.android.support.transition-26.0.0', ext:'aar')
	compile(name: 'common-unity-release', ext:'aar')
	compile(name: 'native-pay-unity-release', ext:'aar')
	compile(name: 'web-pay-unity-release', ext:'aar')
}

6- After installing the generated apk on any android device everything will work fine untill you click on "Add to Cart" button. because Add to cart tries to get Default Client which need 
com.shopify.buy.androidpay.AndroidPayCheckout class but it cannot be found and javaclass not found exception occures.

**Comment by sleroux** [comment]
@nasir41 I'm curious about this step:

` 3- After resolving jar client export the project to Android Studio because on my system Unity does not build with latest build tools.`

Whats the build errors you're seeing? I have a feeling you might be running into a similar issue as https://github.com/Shopify/unity-buy-sdk/issues/507. Could you give this [1] .unitypackage a try and see if you're able to build using Unity? If not you can try exporting the project and use Android Studio and see if that works.

[1] https://github.com/Shopify/unity-buy-sdk/blob/399acee3ffdd70062d7ef10b98952a5d1a37bfeb/shopify-buy.unitypackage

**Comment by sleroux** [comment]
I used the new package I linked and followed your steps. I was able to replicate the same issue and tracked it down. Android Pay is currently unsupported by the SDK - only Web checkouts work at the moment so I've gone ahead and cleared that up.

Would you mind giving https://github.com/Shopify/unity-buy-sdk/raw/02ab1bafacbf58b4024eefa0c7f46f1d9f36ea7c/shopify-buy.unitypackage a try?

**Comment by nasir41** [comment]
Hi sleroux,
Thanks for your great help. Following 
https://github.com/Shopify/unity-buy-sdk/raw/02ab1bafacbf58b4024eefa0c7f46f1d9f36ea7c/shopify-buy.unitypackage
Helped me to get rid of this issue.
