### ISSUE TITLE
image("medium").transformedSrc() always returns 1000x1000 image

### ISSUE THREAD

**Issue by Mitnainartinarian** [Shopify/unity-buy-sdk#512]
I'm trying to get a scaled down image of a product variant, but I'm always getting the same 1000x1000 image even if I specify something smaller. I had it working a while ago in an older version of the SDK (before image.src was deprecated). Is this the correct way to specify the size?

`variant.image("medium").transformedSrc()`

I use this to retrieve the products:

`ShopifyBuy.Client().products((fetchedProducts, err) => {...}, fetchIDs);`

I get the variant from the list returned by product.variants(). The code for transformedSrc is based on the comment for Shopify.Unity.ShopifyClient (on line 139 in ShopifyBuy.cs in v0.5.1 of the Unity SDK). I tried moving the "medium" alias to transformedSrc instead, but it didn't work either.

**Comment by mikkoh** [comment]
@sleroux can we close this?

**Comment by sleroux** [comment]
I've added this fix to the latest v0.5.2 release:

@Mitnainartinarian, to get the image for the given size, the API has slightly changed from:

`variant.image("medium").transformedSrc()`

to

`variant.image().transformedSrc("medium")`
