### ISSUE TITLE
TextMeshPro Rich Text Support for Description

### ISSUE THREAD

**Issue by Dorgam** [Shopify/unity-buy-sdk#513]
Hello,

We are using unity SDK in our project, and we noticed that the description comes only in two flavors: string, or html. While unity, with its plugin TextMeshPro only supports Rich Text.

Is there a shortcut why to transform the html to rich text?

**Comment by mikkoh** [comment]
Sorry for the extremely late reply. Converting HTML to Rich Text is probably outside of the scope of this library.
