### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by kevinfoley** [Shopify/unity-buy-sdk#577]
The Buy SDK internally refers to deprecated fields and then logs deprecation warnings about this:

    The field `ProductVariant.price` is deprecated with the following deprecation message:
    Use `priceV2` instead

    The field `Checkout.subtotalPrice` is deprecated with the following deprecation message:
    Use `subtotalPriceV2` instead

    The field `Checkout.totalTax` is deprecated with the following deprecation message:
    Use `totalTaxV2` instead

    The field `Checkout.totalPrice` is deprecated with the following deprecation message:
    Use `totalPriceV2` instead

    The field `CheckoutCreatePayload.userErrors` is deprecated with the following deprecation message:
    Use `checkoutUserErrors` instead

Presumably, the SDK's internal code should not refer to deprecated fields.

**Comment by rebeccajfriedman** [comment]
I believe this should be fixed, as of https://github.com/Shopify/unity-buy-sdk/pull/580
