### ISSUE TITLE
Product descriptions lose line breaks

### ISSUE THREAD

**Issue by kevinfoley** [Shopify/unity-buy-sdk#578]
Product descriptions loaded through the Buy SDK lose all line breaks, which can make them extremely difficult to read. For example,

    The all new Acme Productifier* contains loads of new features, including:
      - 5 gizmos
      - 2 gadgets
      - 4 widgets
      - Moisture-wicking fabric
      - Gorilla Glass
      - Corrosion-resistant gears
      - Ceramic Heating element**
    Don't be square, reserve yours today!
    * This product contains chemicals known to the state of California to cause cancer, birth defects, or other reproductive harm.
    ** Not available in Iceland, Greenland, Canada, Russia, or Alaska

comes out like this:

> The all new Acme Productifier* contains loads of new features, including: - 5 gizmos  - 2 gadgets - 4 widgets - Moisture-wicking fabric - Gorilla Glass - Corrosion-resistant gears - Ceramic Heating element Don't be square, reserve yours today!* This product contains chemicals known to the state of California to cause cancer, birth defects, or other reproductive harm.** Not available in Iceland, Greenland, Canada, Russia, or Alaska

**Comment by rebeccajfriedman** [comment]
Hi @kevinfoley - There is another field called `descriptionHtml` which will maintain the HTML formatting. 

https://github.com/Shopify/unity-buy-sdk/blob/master/Assets/Shopify/Unity/SDK/DefaultProductQueries.cs#L28

**Comment by kevinfoley** [comment]
@rebeccajfriedman And that's worthless unless we write our own custom browser. There's far too much HTML to parse meaningful text out of it.

The HTML-free description should still include line breaks, using the newline ( \n ) character.
