### ISSUE TITLE
V2.1 iOS build error - built without full bitcode

### ISSUE THREAD

**Issue by kingmoge** [Shopify/unity-buy-sdk#611]
Using Unity 2019.4.20f1 and new Shopify Buy 2.1. Project includes Allegorithmic Substance. Development build.

When publishing for iOS using Unity Cloud Build, we get the following XCode error. The error points to Allegorithmic, but disappears when we roll back to earlier version Shopify Buy.

17241: ▸ ❌;  ld: bitcode bundle could not be generated because '/BUILD_PATH.../temp20210311-6598-1ame9hq/Libraries/Allegorithmic/Plugins/Substance/iOS/libSubstance.Engine.a(md4.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/BUILD_PATH/.../temp20210311-6598-1ame9hq/Libraries/Allegorithmic/Plugins/Substance/iOS/libSubstance.Engine.a' for architecture arm64
17242: ▸ ❌;  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Trying a local XCode build, we get this error related to Substance libalgcompression.a (also does not appear with earlier version of Shopify Buy):
10 duplicate symbols for architecture arm64

**Comment by sleroux** [comment]
The latest release (2.1.1) should have this resolved! The issue was when the static library was built for the .unitypackage, was not generated bitcode for use in an iOS app.
