### ISSUE TITLE
Use the purpler banner from Mobile Buy SDK

### ISSUE THREAD

**Issue by dbart01** [Shopify/unity-buy-sdk#89]
We have some awesome banners to use for the Buy SDK readme:
https://github.com/Shopify/mobile-buy-sdk-ios/issues/620

Shouldn't be to difficult to update `Mobile Buy SDK` to `Unity Buy SDK`.

cc: @Ash-Edmundson

**Comment by Ash-Edmundson** [comment]
@dbart01 is there anything that you need from me here?

**Comment by mikkoh** [comment]
@Ash-Edmundson I think at some point it would be nice to get a similar fancy banner for the Unity Buy SDK to have the SDKs all be branded in a similar fashion. I don't think there's a huge immediate need right now but it's something that would be great to drop in at some point.

**Comment by Ash-Edmundson** [comment]
Alright, I'm not keeping track of what's going on on these projects. If at anytime you will be needing one, I request I get a weeks notice to put something together :)

**Comment by mikkoh** [comment]
Sounds good. Yeah I haven't mentioned it to anyone because right now our focus is getting an landing page up for Gaming. Thanks @Ash-Edmundson 

cc @coreypollock

**Comment by dengjeffrey** [comment]
Now that we have landing page should we revisit this, @coreypollock

**Comment by coreypollock** [comment]
Hey @Ash-Edmundson ! It would be awesome to get a banner for the top of the Unity Buy SDK GitHub repo, here: https://github.com/Shopify/unity-buy-sdk

In terms of the illustration on the banner itself, i'm not sure what to use. On the Unity SDK landing page we show real physical merch from our merchants Alto's Adventure: https://developers.shopify.com/custom-storefront-sdks/unity-buy-sdk

Would love to know what you think, and if you have some capacity to put this together :)

**Comment by Ash-Edmundson** [comment]
I'm a bit over capacity for the next couple weeks, try submitting an issue for the illustration team
https://github.com/Shopify/projects-illustration

They will give you a good idea of what can be created and a timeline around it. If they are unable to make something new, I can potentially put together some existing elements.

**Comment by coreypollock** [comment]
Great! Thanks @Ash-Edmundson - i'll fill out a request form 👍🏼

**Comment by dengjeffrey** [comment]
Finished in #261
